### ISSUE TITLE
Notify shiny dashboard users that service is being decomissioned

### ISSUE THREAD

**Issue by ca-scribner** [StatCan/R-dashboards#39]
* [x] Notify owners of existing dashboards that we will be decomissioning the service
* [x] Inform all current users about other options and what they need to do to get them
* [x] #43
* [x] #44
* [ ] #45

**Comment by ca-scribner** [comment]
@Colette-G I'm adding this into the current sprint.  @YannCoderre if you didn't plan on actually doing this before the end of sprint, please take it back out :)

**Comment by parlerBinou** [comment]
Do you have a timeline for this?
Is it going to be sometime like next month or the end of the year?

**Comment by YannCoderre** [comment]
I know this is coming but unfortunately I do not know the timeline for the decommissioning of the Shinny dashboard just yet. I am currently seeking the details from my manager. As soon as I have some information, I will let you know of the details.

**Comment by YannCoderre** [comment]
Advanced Analytics Workplace (AAW) will be decommissioning the R-Shiny dashboard on Friday September 3, 2021. 
Users / Owners of dashboards will be asked to transfer their projects to the Data Visualizations in Dissemination Division at Statistics Canada. Your point of contact will be Joseph Prince. Joseph and his team have already started to transfer some of the AAW R-shinny dashboard. All that is required is too ZIP your current r-dashboard and send it to Joseph Prince (joseph.prince@canada.ca ) to get the process started.
Please note that the goal is to publish on the Statistics Canada website and the project will need to be in the required template. The current file structure is maintained and we will mimic it when we load the files.  There is also no limitations on the libraries that can be used so that is not an issue.
