### ISSUE TITLE
Handling deletions/renaming in the CI?

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/R-dashboards#8]
In the last merge I removed a little example (it used out-dated features), but it persists on the disk.

Also, there are many apps in the shiny folder being served that don't have the disclaimer banners

![sreenshot-2020-04-23_18-04-1587681431](https://user-images.githubusercontent.com/10801138/80156274-849f3580-8591-11ea-979f-a966ce78f515.png)

Should we remove these?

**Comment by blairdrummond** [comment]
Update, I manually removed the dashboard from R-dashboards for now, but wanted to give the headsup.

**Comment by ca-scribner** [comment]
#37 hit this same issue.  They updated their app in a way that removed, rather than modified, some of the old code.  When pushed to the file share, this left the "deleted" files sitting in the directory alongside the new/updated files, which broke the dashboard.  Should we be doing a different sync process whenever this repo updates?
